### ISSUE TITLE
Root url settings?

### ISSUE THREAD

**Issue by istack-robel** [Atyantik/react-pwa#86]
Is there a way we can specify a root url so the build wont assume that we will be deploying to something like www.example.com or sub.example.com? I wanted my app to be access to like example.com/myapp or example.com/myapp/another-dir. Thank you!

**Comment by tirthbodawala** [comment]
That is very interesting. Haven't thought of it with that reference. Let me look into it. Thanks for raising the issue. Will look into it for sure.

**Comment by danfsd** [comment]
I'm think that I'm having the same issue:
I'm trying to run the application in a server that has other projects running at the same time. So I'm mounting the application on `myserver.com/projects/my-pwa`, but the application is trying to fetch all assets' paths from `myserver.com/build/images` instead of `myserver.com/projects/my-pwa/build/images`.

Any clues if this issue is the same from the OP?

**Comment by tirthbodawala** [comment]
@danfsd @istack-robel: Have found a solution to this, would add a patch soon.

**Comment by tirthbodawala** [comment]
This is now feasible with PawJS v2 Implementation. checkout the latest repo changes and update the pawconfig.js to change your root url:
```
  "appRootUrl": "/myapp",
```

**Comment by danfsd** [comment]
Thanks for the effort, will check it soon.

**Comment by istackservices** [comment]
Cool! Thank you!
